### ISSUE TITLE
Crash when receiving AIM message lol

### ISSUE THREAD

**Issue by dequis** [gkdr/lurch#31]
lol

```
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f1e11b4204f in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f1e18f45f80 (LWP 26756))]
(gdb) bt
#0  0x00007f1e11b4204f in raise () at /usr/lib/libc.so.6
#1  0x00007f1e11b4347a in abort () at /usr/lib/libc.so.6
#2  0x000056377897e629 in sighandler (sig=<optimized out>) at gtkmain.c:179
#3  0x00007f1e11b420b0 in <signal handler called> () at /usr/lib/libc.so.6
#4  0x00007f1e11b8f446 in strlen () at /usr/lib/libc.so.6
#5  0x00007f1dfced118c in axc_session_exists_any () at /home/dx/.purple/plugins/lurch.so
#6  0x00007f1dfcec8ac1 in lurch_topic_update_im (conv_p=0x56377a0b2b00) at ./src/lurch.c:2234
#7  0x00007f1dfcec8da0 in lurch_conv_updated_cb (conv_p=0x56377a0b2b00, type=PURPLE_CONV_UPDATE_TITLE) at ./src/lurch.c:2309
#8  0x00007f1e15113820 in purple_signal_emit_vargs (instance=<optimized out>, signal=0x7f1e15168739 "conversation-updated", args=args@entry=0x7ffc03a52440) at signals.c:482
#9  0x00007f1e1511398a in purple_signal_emit (instance=<optimized out>, signal=<optimized out>) at signals.c:434
#10 0x00007f1e150dbcdc in purple_conversation_new (type=type@entry=PURPLE_CONV_TYPE_IM, account=account@entry=0x563779c45a80, name=name@entry=0x56377a78a350 "AOL System Msg") at conversation.c:442
#11 0x00007f1e151122d1 in serv_got_im (gc=gc@entry=0x56377a663f20, who=<optimized out>, msg=msg@entry=0x56377a6e34f0 "Hello. Effective 3/28, we will no longer support connections to the AIM network via this method. If you wish to use the free consumer AIM product, we invite you to visit <a href=\"http://www.aim.com/\">www.aim.com</a> for more information.", flags=<optimized out>, flags@entry=(unknown: 0), mtime=1488322528) at server.c:624
#12 0x00007f1dfe3f7171 in incomingim_chan1 (conn=<optimized out>, userinfo=<optimized out>, args=<optimized out>, od=<optimized out>) at oscar.c:1727
#13 0x00007f1dfe3f7171 in purple_parse_incoming_im (od=<optimized out>, conn=<optimized out>, fr=<optimized out>) at oscar.c:2184
#14 0x00007f1dfe3e2cdf in incomingim_ch1 (mod=<optimized out>, cookie=0x56377a0b5a50 "\340\377\265X", bs=<optimized out>, userinfo=0x7ffc03a52820, channel=1, snac=0x7ffc03a52b00, frame=0x56377a7d45b0, conn=0x56377a7d4540, od=0x56377a6640e0) at family_icbm.c:1023
#15 0x00007f1dfe3e2cdf in incomingim (od=0x56377a6640e0, conn=0x56377a7d4540, mod=<optimized out>, frame=0x56377a7d45b0, snac=0x7ffc03a52b00, bs=<optimized out>) at family_icbm.c:1511
#16 0x00007f1dfe3e34b5 in snachandler (od=0x56377a6640e0, conn=0x56377a7d4540, mod=<optimized out>, frame=0x56377a7d45b0, snac=0x7ffc03a52b00, bs=0x56377a7d45b8) at family_icbm.c:2118
#17 0x00007f1dfe3ecd78 in parse_snac (frame=0x56377a7d45b0, conn=0x56377a7d4540, od=0x56377a6640e0) at flap_connection.c:776
#18 0x00007f1dfe3ecd78 in parse_flap (frame=0x56377a7d45b0, conn=0x56377a7d4540, od=0x56377a6640e0) at flap_connection.c:862
#19 0x00007f1dfe3ecd78 in flap_connection_recv (conn=0x56377a7d4540) at flap_connection.c:985
#20 0x0000563778964fe1 in pidgin_io_invoke (source=<optimized out>, condition=<optimized out>, data=0x56377a7e0ca0) at gtkeventloop.c:73
#21 0x00007f1e12f2845a in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#22 0x00007f1e12f28810 in  () at /usr/lib/libglib-2.0.so.0
#23 0x00007f1e12f28b32 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#24 0x00007f1e17b973a7 in gtk_main () at /usr/lib/libgtk-x11-2.0.so.0
#25 0x0000563778928c92 in main (argc=<optimized out>, argv=<optimized out>) at gtkmain.c:939
```

```
(gdb) frame 6
#6  0x00007f1dfcec8ac1 in lurch_topic_update_im (conv_p=0x56377a0b2b00) at ./src/lurch.c:2234
2234      ret_val = axc_session_exists_any(partner_name_bare, axc_ctx_p);
(gdb) p partner_name_bare
$1 = 0x0
(gdb) p axc_ctx_p
$2 = (axc_context *) 0x56377a7d40f0
(gdb) p partner_name
$3 = 0x56377a0b6880 "AOL System Msg"
```

```c
2218      partner_name_bare = jabber_get_bare_jid(partner_name);
```

**Comment by dequis** [comment]
```
20:01 < EionRobb> dx: I thought he caught that one already?
20:01 < dx> dang
20:01 < dx> am i using an outdated thing?
20:02 < EionRobb> https://github.com/gkdr/lurch/issues/18
20:02 < EionRobb> too slow, old man
```

**Comment by EionRobb** [comment]
Rude

**Comment by dequis** [comment]
ty
